### ISSUE TITLE
Very high CPU Load after a few hours

### ISSUE THREAD

**Issue by pkuehnel** [tobiasehlert/teslamateapi#8]
I'm experiencing very high CPU load after using TeslaMateApi a few hours. I have two services calling the API (car/id/status endpoint), one of them every 15 seconds and the other one every 27 seconds and after a few hours (I checked after 15) CPU load of my 4 core Intel Xeon is at 99% when I restart the teslamateApi Docker container everything is back to normal but after a few hours it's up again. I checked my running processes on the debian system where docker is running on and there were multiple TeslaMateApi processes. One time I started (by accident) the container without any open ports, there was no issue, so I think the issue only occurs when my two services call the endpoint. Maybe an issue when API calls are at the same time or something like that?

**Comment by tobiasehlert** [comment]
Hi @pkuehnel 

Interesting finding from you!

1. Is it possible that you disable one of the scheduled requests to see if this behavior appears when doing simultaneous requests towards the status endpoint?
2. Do you see some weird errors showing up in the logs from the TeslaMateApi container?

One theory I got is that the agent connecting to mosquitto does reuse the same name. Maybe running a randomized string at the end could help in this case.. but lets take that in the next step.

Regards,
Tobias

**Comment by pkuehnel** [comment]
I disabled one part of the service, so currently only one request every 27 seconds. I will give you an update in a few hours.
I do not see anything weird in the logfiles:

```

[GIN] 2021/03/09 - 15:46:33 | 200 |  103.852698ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:46:39 | 200 |  105.348825ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:46:33 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:46:23 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:46:23 | 200 |  104.871516ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:46:08 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:46:08 | 200 |    109.4236ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:46:06 | 200 |  104.156904ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:45:52 | 200 |  101.696859ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:46:06 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:45:52 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:45:39 | 200 |  103.114585ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:45:39 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:45:37 | 200 |  107.148859ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:45:37 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:45:22 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:45:22 | 200 |  114.078086ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:45:12 | 200 |   103.33949ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:45:12 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:45:07 | 200 |  104.105003ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:45:07 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:44:51 | 200 |  111.361936ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:44:51 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:44:45 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:44:45 | 200 |  107.795371ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:44:36 | 200 |  105.028021ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:44:36 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:44:21 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:44:21 | 200 |  103.564894ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:44:18 | 200 |  109.215397ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:44:18 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:44:06 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:44:06 | 200 |  121.532722ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:43:51 | 200 |  102.972384ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:43:51 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:43:50 | 200 |  102.635377ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:43:50 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:43:35 | 200 |  103.747597ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:43:35 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:43:24 | 200 |  121.741127ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:43:24 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:43:19 | 200 |  103.956702ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:43:19 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
2021/03/09 15:43:04 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:43:04 | 200 |  115.456512ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:42:57 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:42:57 | 200 |  102.687778ms |   192.168.1.212 | GET      "/cars/1/status",
[GIN] 2021/03/09 - 15:42:49 | 200 |  109.464503ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:42:49 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:42:34 | 200 |  103.310091ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:42:34 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:42:30 | 200 |  111.551942ms |   192.168.1.212 | GET      "/cars/1/status",
2021/03/09 15:42:30 [TeslaMateApi] TeslaMateAPICarsStatus executed /cars/1/status successful.,
[GIN] 2021/03/09 - 15:42:19 | 200 |   105.98014ms |   192.168.1.212 | GET      "/cars/1/status"
```

**Comment by pkuehnel** [comment]
Same issue with only one service calling every 27 seconds but takes longer until this high CPU load is reached:
![htop Screenshot](https://user-images.githubusercontent.com/35361981/110595672-9b855100-817e-11eb-8606-3d532d3d9eb9.PNG)

**Comment by tobiasehlert** [comment]
@pkuehnel, alright!

One question, does the same thing happen if you run towards another endpoint? Lets say `/api/v1/cars`.
Just to see if the main difference here could be something with mosquitto integration.

Meanwhile I am running a curl on the status endpoint every second for a couple of hours to see, if I can reproduce this as well.

**Comment by tobiasehlert** [comment]
@pkuehnel been running for 2,5 hours straight with a curl request every second (so around 10k requests by now).

`[tobias@teslamate-001 ~]$ watch -n 1 "date; curl -s https://teslamate.thelindberg.com/api/v1/cars/1/status"`

When starting (on my single core vmware host with 2 GB ram), the CPU was around 10-12% and it's still at the same level.

![image](https://user-images.githubusercontent.com/4417850/110785258-0744e800-826b-11eb-8fa2-bfbe1ef67575.png)

Here is a picture from ESXi host showing no increase over one hour:

![image](https://user-images.githubusercontent.com/4417850/110785063-c77e0080-826a-11eb-8304-8ec09d86fc8b.png)

Are you using other endpoints during that time or do you only use the status endpoint?

What version of TeslaMateApi are you using?

**Comment by pkuehnel** [comment]
Hmm... I upgraded yesterday to the latest version, but still no difference. Today it took about 6 hours until CPU load was this high. I will try another endpoint the next few days.

**Comment by LelandSindt** [comment]
@tobiasehlert I spent some time looking at this tonight. A new MQTT connection and subscription is made for each, yes?

**Comment by LelandSindt** [comment]
@pkuehnel  

Do you see `Client teslamateapi already connected, closing old connection.` in your Mosquitto logs?

**Comment by LelandSindt** [comment]
My theory... concurrent calls to /api/v1/cars/:CarID/status cause concurrent connections to Mosquitto. Mosquitto drops the first of the two concurrent connections, and TeslamateApi is not handling the disconnect completely.

**Comment by LelandSindt** [comment]
Interesting.. I just saw another behaviour that I don't yet understand... @pkuehnel  do you see `Client <unknown> has exceeded timeout, disconnecting.` in your Mosquitto logs?

**Comment by LelandSindt** [comment]
And because my subconscious can't let problems remain unresolved... This: https://github.com/tobiasehlert/teslamateapi/compare/main...gaussmeter:mqtt fixed the `Client teslamateapi already connected, closing old connection.` issue for me... which may negate the "need" to re-work this feature to maintain a persistent connection to Mosquitto... 

`Client <unknown> has exceeded timeout, disconnecting.` in my environment _may_ be due to my use of `kubefwd` in my development environment... :shrug: it seems to have gone away after running _everything inside_ my k3s cluster...

I am running... `while true; do curl -X GET teslamateapi:8080/api/v1/cars/1/status; done` against an instance of `TeslaMateApi` with my changes to see if I can get it to consume excessive CPU...

**Comment by pkuehnel** [comment]
@LelandSindt I have tons of these messages:
```
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: New connection from 172.21.0.6 on port 1883.,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
1615882389: Client teslamateapi already connected, closing old connection.,
1615882389: New client connected from 172.21.0.6 as teslamateapi (p2, c1, k2).,
```

**Comment by pkuehnel** [comment]
> Client <unknown> has exceeded timeout, disconnecting.

No, I don't have these errors.

**Comment by tobiasehlert** [comment]
> @tobiasehlert I spent some time looking at this tonight. A new MQTT connection and subscription is made for each call to `/api/v1/car/:CarID/status` , yes?

I guess you found it in the code.. the request to status endpoint creates a MQTT connection on request and it does disconnect afterwards.

> If I were to re-work this feature, I think I would maintain a persistent connection to Mosquitto, subscribe to all cars and store their state locally, returning the current stored state upon a call to `/api/v1/cars/:CarID/status`

Yeah you are right about that. Maybe the MQTT connection should be setup similar to the DB connection at start of the container. And then somehow store the data in memory or make the subscribe (and unsubscribe) when accessing the /status endpoint
 
> That said... Opinion nobody asked for: I don't see a lot of value in this endpoint, as I would much prefer to simply subscribe to to the MQTT message queue.

Both yes or no.. I get your point there, but if you consume other parts of the API in a tool you build and you just want the current status as well the same way, that would be easy and fast to use.

**Comment by tobiasehlert** [comment]
@pkuehnel there is a docker image with tag bug-8 that you could try to see, if the change from @LelandSindt helped.
Please let us know how it works!

**Comment by pkuehnel** [comment]
I updated it an will let you know.

**Comment by LelandSindt** [comment]
My overnight testing still saw high CPU utilization from `TeslaMateApi`, but I didn't see any `Client teslamateapi already connected, closing old connection.` 

I added a`defer` to the MQTT disconnection: https://github.com/tobiasehlert/teslamateapi/compare/bug-8...gaussmeter:mqtt and am testing now..

**Comment by tobiasehlert** [comment]
> My overnight testing still saw high CPU utilization from `TeslaMateApi`, but I didn't see any `Client teslamateapi already connected, closing old connection.`

@LelandSindt 
Great you could recreate it! I did not get that on my two TeslaMate installations..

> I added a`defer` to the MQTT disconnection: [bug-8...gaussmeter:mqtt](https://github.com/tobiasehlert/teslamateapi/compare/bug-8...gaussmeter:mqtt) and am testing now..

Merged the defer to bug-8 in PR #16.. should be built and release on Docker Hub in some minutes :)

@pkuehnel
Run a pull on the latest bug-8 label and test :)

**Comment by LelandSindt** [comment]
I continued to see high CPU utilization from `TeslaMateApi` after 4 concurrent sets of  `while true; do curl -X GET teslamateapi:8080/api/v1/cars/1/status; done`

Interestingly I also saw high CPU utilization from `mosquitto` and `coredns` which both recover after `TeslaMateApi` is restarted.

My config is nothing special but can be seen here: https://github.com/wizardlyEinstein/teslamateapi 

At this point, I am out of ideas... save for a rewrite to make the MQTT connection and subscriptions persistent.

**Comment by tobiasehlert** [comment]
@LelandSindt

Interesting finding regarding your higher CPU load. My two day test that I've done didn't increase the load at all, so I can't recreate it.

But what you think by doing a persistent subscription instead than doing a connect when calling the endpoint?
I think this should be similar to establishing the DB connection in this case.. except that we do a subscribe and unsubscribe on the topics when receiving the endpoint call.
Or do you rather think that we should make a persistent subscribe and also store the topic information in memory to not require a subscribe/unsubscribe on every call of the endpoint?

**Comment by LelandSindt** [comment]
@tobiasehlert 

Persistent subscriptions would eliminate the need for a sleep, which could continue to require environment specific tuning. 

That said... a persistent connection would require connection handling. I use this: https://github.com/gaussmeter/mqttagent

**Comment by tobiasehlert** [comment]
@LelandSindt added an issue to the github repo of the library we are using.. lets hope they have some idea for this.

https://github.com/eclipse/paho.mqtt.golang/issues/491

**Comment by pkuehnel** [comment]
For me the CPU issue is resolved with bug-8 tag.

**Comment by LelandSindt** [comment]
witth @pkuehnel's comment that his issue is resolved... I reviewed my config/logs/etc... I think I have stumbled onto a new/different bug... details to follow this evening.

**Comment by LelandSindt** [comment]
This morning with a fresh instance of TeslaMateApi running, I started `while true; do curl -X GET teslamateapi:8080/api/v1/cars/1/status; done` in 4 terminals. 

Some time later I found TeslaMateApi running at over %100 CPU. 

![Screenshot from 2021-03-17 10-55-58](https://user-images.githubusercontent.com/939903/111543310-dff58b80-8740-11eb-8fa1-5964e13c9ab3.png)

I stopped all 4 curl loops, but TeslaMateApi continued to consume over 100% CPU. 

![Screenshot from 2021-03-17 10-56-58](https://user-images.githubusercontent.com/939903/111543408-03b8d180-8741-11eb-8363-bd75ce33eb4b.png)

TeslaMateApi's logs went quiet (no new entries) as expected, but Mosquitto's logs were still showing entries at an impressive pace... 

```
1615997072: New client connected from 10.42.0.93 as teslamateapi-TA6x (p2, c1, k2).
1615997072: New connection from 10.42.0.93 on port 1883.
1615997072: Client teslamateapi-TA6x already connected, closing old connection.
1615997072: New client connected from 10.42.0.93 as teslamateapi-TA6x (p2, c1, k2).
1615997072: New connection from 10.42.0.93 on port 1883.
1615997072: Client teslamateapi-TA6x already connected, closing old connection.
1615997072: New client connected from 10.42.0.93 as teslamateapi-TA6x (p2, c1, k2).
1615997072: New connection from 10.42.0.93 on port 1883.
1615997072: Client teslamateapi-TA6x already connected, closing old connection.
```

note: The client `teslamateapi-TA6x` is the same... This went on for hours, until I finally restarted TeslaMateApi.

Perhaps this is/should be a new issue.

**Comment by LelandSindt** [comment]
I am testing with these changes https://github.com/tobiasehlert/teslamateapi/compare/bug-8...gaussmeter:mqtt

Trying to address @MattBrittan's suggestion... 

> You are calling m.Disconnect(250) or defer m.Disconnect(250) (depending upon revision) from inside a loop but only connecting once (outside of the loop). You need to decide whether the connection should stay up for the whole loop or if a new connection should be established on each iteration (and using defer inside a loop is not really recommended!).

... and added some logging.

**Comment by LelandSindt** [comment]
Still seeing the behaviour described here: https://github.com/tobiasehlert/teslamateapi/issues/8#issuecomment-801473425 with my changes... 

I had hoped that I would be able to see something in TeslaMateApi logs but I think they rolled before I could catch them... 

:man_shrugging:  I am out of ideas at this time.

**Comment by MattBrittan** [comment]
How about something [like this](https://github.com/MattBrittan/teslamateapi/commit/3535cdc404a8e9375f9ea8755d49a4e16ebf0a8ci) - it's a bit rough (and untested due to @LelandSindt being unprepared to supply a Tesla for testing) but think this design would work better...

**Comment by LelandSindt** [comment]
@MattBrittan I envy your ability to attempt a rewrite on a routine you can't test :smile: 

My quick test this morning resulted in a panic...  

```
2021/03/18 12:06:43.369574 [info] TeslaMateApi running in release mode.
panic: assignment to entry in nil map
goroutine 67 [running]:
main.(*statusCache).newMessage(0xc0001d3aa0, 0x989c68, 0xc0001d6c00, 0x987078, 0xc0002a85a0)
        /go/src/v1_TeslaMateAPICarsStatus.go:180 +0x1dc5
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1.1(0xc000292970, 0xc0001d6c00, 0x987078, 0xc0002a85a0)
        /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.2/router.go:150 +0x50
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func1
        /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.2/router.go:149 +0x250
```

I will have another look over my lunch break.  --- Thank you!

**Comment by MattBrittan** [comment]
@LelandSindt had forgotten to make the map - have pushed out a fix (not so great at writing code I cannot test!).

**Comment by LelandSindt** [comment]
@MattBrittan it built and is running without issue. 

I have yet to dig deep/thoroughly review, but it looks good so far!

If its not too much to ask, I have some questions about MQTT connection management/recovery for another [project I maintain](https://github.com/gaussmeter/teslamater). Once I have some time to summarize, should I bring them up in the https://github.com/eclipse/paho.mqtt.golang issues?

**Comment by LelandSindt** [comment]
I load tested @MattBrittan's refactor for a few days and never had any issues.

@tobiasehlert what are your thoughts?

**Comment by tobiasehlert** [comment]
> @tobiasehlert what are your thoughts?

I think it looks good @LelandSindt.. I'm not 100% sure what happens in the different functions, but from what I can see it looks good actually.

A lot of thanks to @MattBrittan for the help! Sad I don't have any spare-cash to buy you a Tesla.. not even my wife did get one either hehe

**Comment by tobiasehlert** [comment]
@LelandSindt have you some PR ready with the code by Matt from https://github.com/MattBrittan/teslamateapi?

**Comment by MattBrittan** [comment]
@tobiasehlert - I'll push the code as it stands (don't think Leland made any adjustments) and you can do whatever you like with it from there.

**Comment by tobiasehlert** [comment]
@pkuehnel is this issue still existing for you or is everything green? :)
If it's working as expected now I'll close the ticket.

**Comment by pkuehnel** [comment]
I's working as expected but I'm still on the bug-8 Tag. Should i change it to latest and try again?

**Comment by tobiasehlert** [comment]
@pkuehnel oh.. I missed that the branch was done.. merging it in a couple of minutes so you should be able to switch to latest very soon :)
